/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinadoresRouteImport } from './routes/treinadores'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PaisesRouteImport } from './routes/paises'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as ConfiguracaoRouteImport } from './routes/configuracao'
import { Route as ClubesRouteImport } from './routes/clubes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreinadoresNameRouteImport } from './routes/treinadores.$name'
import { Route as PaisesNameRouteImport } from './routes/paises.$name'
import { Route as ClubesNameRouteImport } from './routes/clubes.$name'

const TreinadoresRoute = TreinadoresRouteImport.update({
  id: '/treinadores',
  path: '/treinadores',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PaisesRoute = PaisesRouteImport.update({
  id: '/paises',
  path: '/paises',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracaoRoute = ConfiguracaoRouteImport.update({
  id: '/configuracao',
  path: '/configuracao',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesRoute = ClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinadoresNameRoute = TreinadoresNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => TreinadoresRoute,
} as any)
const PaisesNameRoute = PaisesNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => PaisesRoute,
} as any)
const ClubesNameRoute = ClubesNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ClubesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clubes': typeof ClubesRouteWithChildren
  '/configuracao': typeof ConfiguracaoRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/importar': typeof ImportarRoute
  '/paises': typeof PaisesRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/treinadores': typeof TreinadoresRouteWithChildren
  '/clubes/$name': typeof ClubesNameRoute
  '/paises/$name': typeof PaisesNameRoute
  '/treinadores/$name': typeof TreinadoresNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clubes': typeof ClubesRouteWithChildren
  '/configuracao': typeof ConfiguracaoRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/importar': typeof ImportarRoute
  '/paises': typeof PaisesRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/treinadores': typeof TreinadoresRouteWithChildren
  '/clubes/$name': typeof ClubesNameRoute
  '/paises/$name': typeof PaisesNameRoute
  '/treinadores/$name': typeof TreinadoresNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clubes': typeof ClubesRouteWithChildren
  '/configuracao': typeof ConfiguracaoRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/importar': typeof ImportarRoute
  '/paises': typeof PaisesRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/treinadores': typeof TreinadoresRouteWithChildren
  '/clubes/$name': typeof ClubesNameRoute
  '/paises/$name': typeof PaisesNameRoute
  '/treinadores/$name': typeof TreinadoresNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clubes'
    | '/configuracao'
    | '/hall-of-fame'
    | '/importar'
    | '/paises'
    | '/rankings'
    | '/treinadores'
    | '/clubes/$name'
    | '/paises/$name'
    | '/treinadores/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clubes'
    | '/configuracao'
    | '/hall-of-fame'
    | '/importar'
    | '/paises'
    | '/rankings'
    | '/treinadores'
    | '/clubes/$name'
    | '/paises/$name'
    | '/treinadores/$name'
  id:
    | '__root__'
    | '/'
    | '/clubes'
    | '/configuracao'
    | '/hall-of-fame'
    | '/importar'
    | '/paises'
    | '/rankings'
    | '/treinadores'
    | '/clubes/$name'
    | '/paises/$name'
    | '/treinadores/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubesRoute: typeof ClubesRouteWithChildren
  ConfiguracaoRoute: typeof ConfiguracaoRoute
  HallOfFameRoute: typeof HallOfFameRoute
  ImportarRoute: typeof ImportarRoute
  PaisesRoute: typeof PaisesRouteWithChildren
  RankingsRoute: typeof RankingsRoute
  TreinadoresRoute: typeof TreinadoresRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treinadores': {
      id: '/treinadores'
      path: '/treinadores'
      fullPath: '/treinadores'
      preLoaderRoute: typeof TreinadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paises': {
      id: '/paises'
      path: '/paises'
      fullPath: '/paises'
      preLoaderRoute: typeof PaisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracao': {
      id: '/configuracao'
      path: '/configuracao'
      fullPath: '/configuracao'
      preLoaderRoute: typeof ConfiguracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes': {
      id: '/clubes'
      path: '/clubes'
      fullPath: '/clubes'
      preLoaderRoute: typeof ClubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinadores/$name': {
      id: '/treinadores/$name'
      path: '/$name'
      fullPath: '/treinadores/$name'
      preLoaderRoute: typeof TreinadoresNameRouteImport
      parentRoute: typeof TreinadoresRoute
    }
    '/paises/$name': {
      id: '/paises/$name'
      path: '/$name'
      fullPath: '/paises/$name'
      preLoaderRoute: typeof PaisesNameRouteImport
      parentRoute: typeof PaisesRoute
    }
    '/clubes/$name': {
      id: '/clubes/$name'
      path: '/$name'
      fullPath: '/clubes/$name'
      preLoaderRoute: typeof ClubesNameRouteImport
      parentRoute: typeof ClubesRoute
    }
  }
}

interface ClubesRouteChildren {
  ClubesNameRoute: typeof ClubesNameRoute
}

const ClubesRouteChildren: ClubesRouteChildren = {
  ClubesNameRoute: ClubesNameRoute,
}

const ClubesRouteWithChildren =
  ClubesRoute._addFileChildren(ClubesRouteChildren)

interface PaisesRouteChildren {
  PaisesNameRoute: typeof PaisesNameRoute
}

const PaisesRouteChildren: PaisesRouteChildren = {
  PaisesNameRoute: PaisesNameRoute,
}

const PaisesRouteWithChildren =
  PaisesRoute._addFileChildren(PaisesRouteChildren)

interface TreinadoresRouteChildren {
  TreinadoresNameRoute: typeof TreinadoresNameRoute
}

const TreinadoresRouteChildren: TreinadoresRouteChildren = {
  TreinadoresNameRoute: TreinadoresNameRoute,
}

const TreinadoresRouteWithChildren = TreinadoresRoute._addFileChildren(
  TreinadoresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubesRoute: ClubesRouteWithChildren,
  ConfiguracaoRoute: ConfiguracaoRoute,
  HallOfFameRoute: HallOfFameRoute,
  ImportarRoute: ImportarRoute,
  PaisesRoute: PaisesRouteWithChildren,
  RankingsRoute: RankingsRoute,
  TreinadoresRoute: TreinadoresRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
